
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gslides
    username: gslides
    password: gslides
  jpa:
#    hibernate:
#      ddl-auto: <create | create-drop | update | validate | none>
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
